import Head from 'next/head'
import "98.css";
import React from "react"
import Link from 'next/link';




export default function Test() {
    const [count, setCount] = React.useState(0);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{ width: 300, position:"absolute", bottom: 500, left: 600 }} className="window">
                <div className="title-bar">
                    <div className="title-bar-text">Counter</div>
                    <div className="title-bar-controls">
                        <button aria-label="Minimize" />
                        <button aria-label="Maximize" />
                        <button aria-label="Close" />
                    </div>
                </div>

                <div className="window-body">
                    <p style={{ textAlign: "center" }}>Current count: {count}</p>
                    <div className="field-row" style={{ justifyContent: "center" }}>
                        <button onClick={() => setCount(count + 1)}>+</button>
                        <button onClick={() => setCount(count - 1)}>-</button>
                        <button onClick={() => setCount(0)}>0</button>
                    </div>
                </div>
            </div>
            <footer className='title-bar' style={{ position: "absolute", bottom: 0, width: "100%" }}>
        <Link href="/"><button className='button'>Back</button></Link>

      </footer>
        </div>


    )
}